---
- name: Config HammerDB
  hosts: hammer
  become: true
  vars:
    postgres_ip: "{{ postgres_ip }}"
  tasks:
    - name: Unset LD_LIBRARY_PATH
      shell: 
        cmd: unset LD_LIBRARY_PATH
        chdir: HammerDB-4.1

    - name: Export LD_LIBRARY_PATH
      shell: 
        cmd: export LD_LIBRARY_PATH=/usr/lib/postgresql/14/lib
        chdir: HammerDB-4.1

    - name: Write file contents
      copy:
        content: |
            dbset db pg
            dbset bm tpc-c
            diset connection pg_host {{ postgres_ip }}
            diset tpcc pg_count_ware 2
            diset tpcc pg_num_vu 2
            diset tpcc pg_superuserpass admin
            buildschema
            vudestroy
        dest: HammerDB-4.1/hammerdb_arguments.tcl

    - name: Run test commands
      shell:
        cmd: ./hammerdbcli auto hammerdb_arguments.tcl
        chdir: HammerDB-4.1
      register: test_op

    - name: Display test_op
      debug:
        var: test_op
